spring:
    application:
      name: "ecommerce"

    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

    output:
      ansi:
        enabled: always

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: ${SHOW_SQL:false}
      defer-datasource-initialization: true

    sql:
      init:
        mode: always
        encoding: UTF-8

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 30 # minutos
      refresh-expiration: 300 # minutos
    cookies:
      secure: ${COOKIES_SECURE:false}  # true en HTTPS/producci√≥n
      same-site: ${COOKIES_SAME_SITE:Lax}  # None para HTTPS+CORS, Lax para local

#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ###
#            client-secret:

server:
  port: ${PORT:8080}